/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
const { v4: uuidv4 } = require('uuid');
const fs = require('fs');
const todo_list_path = './files/data.json'

// Import the data from the previously saved session/database
// Cast the entries into a map with the help of converting the 
// imported data into json object
var list_of_todos = require(todo_list_path)
list_of_todos = new Map(Object.entries(JSON.parse(JSON.stringify(list_of_todos))));

const app = express();

app.use(bodyParser.json());

function write_to_disk(err){
  if (err) {
    console.log(err)
  } 
};

// Earlier, we used to define a list of todos afresh, now
// We have already loaded it from our database i.e. file from above
// var list_of_todos = new Map();

// Helper function which converts a map into a list
function map_to_array(){
  var list_of_items = [];
  for (let [key, value] of list_of_todos) {
    list_of_items.push(value);
  }
  return list_of_items;
}

// Handler for the get route, gets all the items in the todolist
function get_todos(req, res){
  res.status(200).send(map_to_array());
}

// Hanlder for get individual todo route, given an ID, get the todos
function get_individual_todo(req, res){
  const req_id = req.params.id;

  // Search for the id in the list of todos
  if (list_of_todos.has(req_id)){
    res.status(200).send(list_of_todos.get(req_id))
  }

  res.status(404).send("Not Found");
}

// Handler for creating a todo item
function create_todo(req, res){
  var req_body = req.body;
  const req_id = uuidv4();
  req_body.id = req_id;
  list_of_todos.set(req_id, req_body);
  
  // Log this change to the local file system to persist the change
  fs.writeFile(todo_list_path, JSON.stringify(list_of_todos), write_to_disk)

  res.status(201).send({id: req_id});
}

// Handler to update a todo item
function update_todo_item(req, res) {

  const req_id = req.params.id;
  const new_body = req.body;

  // Search for the id in the list of todos
  if (list_of_todos.has(req_id)) {
    new_body.id = req_id
    list_of_todos[req_id] = new_body;

    // Log this change to the local file system to persist the change
    fs.writeFile(todo_list_path, JSON.stringify(list_of_todos), write_to_disk)

    res.status(200).send("Updated")
  }
  else {
    res.status(404).send("Not Found");
  }
}

// Handler to delet a todoitem from the list
function delete_todo_item(req, res) {

  const req_id = req.params.id;

  // Search for the id in the list of todos
  if (list_of_todos.has(req_id)) {
    list_of_todos.delete(req_id);

    // Log this change to the local file system to persist the change
    fs.writeFile(todo_list_path, JSON.stringify(list_of_todos), write_to_disk)

    res.status(200).send("Deleted")
  }
  else {
    res.status(404).send("Not Found");
  }
}

// Register the handlers with the routes
app.get("/todos", get_todos)
app.get("/todos/:id", get_individual_todo)
app.post("/todos", create_todo)
app.put("/todos/:id", update_todo_item)
app.delete("/todos/:id", delete_todo_item)

// Maintain this route to handle any non-existent route
app.get("/:any", function(req, res){
  res.status(404).send("Route does not exist")
})

module.exports = app;
